name: Build APK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip build-essential git python3 python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
      
      - name: Install Buildozer
        run: |
          pip3 install --user buildozer
          echo "Buildozer version:"
          buildozer --version
      
      - name: List files
        run: |
          echo "Current directory contents:"
          ls -la
          echo "Python version:"
          python3 --version
          echo "Pip version:"
          pip3 --version
      
      - name: Build APK
        run: |
          buildozer android debug -v
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: bin/*.apk 
